name: Test

on:
  pull_request:
    paths:
      - "**.py"
  push:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  pytest:
    strategy:
      matrix:
        python-version: ["3.11"]
    runs-on: ubuntu-latest
    name: Pytest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install project
        run: poetry install
      - name: Format
        run: make fmt && git diff --exit-code .
      - uses: AustinScola/mypy-cache-github-action@v1
        name: Cache mypy cache
      - name: Lint
        run: make lint
      - name: Run Test
        run: make test
